name: joo_store
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#--------------PACKAGES------------------#
dependencies:
  flutter:
    sdk: flutter


  #Utilis Packages
  http: ^1.2.2
  intl: ^0.20.0
  logger: ^2.5.0
  url_launcher: ^6.3.1

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0


  #State Management (GET X)
  get: ^4.6.6
  get_storage: ^2.1.1

  #Product Specific

  #--------------/PACKAGES------------------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/brand/